version: '3.8'

services:

  mysql:
    image: mysql/mysql-server:latest
    container_name: mysql_desafio
    restart: always
    environment:
      - MYSQL_DATABASE=db_desafio
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - '3307:3306'
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    networks:
      - network

networks:
  network:
    driver: bridge